import path from 'path'
import fs from 'fs-extra'
import { Asset, Scene, Node } from 'gltf-builder';
import slugify from '@sindresorhus/slugify'

const TARGET_DIR = process.env.STORY_TARGET_DIR ?? process.cwd();

const storyTemplate = (importPath: string, title: string) => `// Autogenerated
import { gltfStoryTemplate } from '@gengarden/examples/build/lib/story-template';
import gltfAsset from 'file-loader!./${importPath}';

export default {
  title: '${title}',
};

export const GLTFModel = gltfStoryTemplate({ src: gltfAsset });
`

export const generateGLTFStory = async (title: string, model: Node) => {
  const slug = slugify(title)

  const assetFilename = `${slug}.gltf`
  const assetPath = path.resolve(TARGET_DIR, assetFilename)
  const gltf = new Asset().addScene(new Scene().addNode(model)).build();

  await fs.ensureFile(assetPath)
  await fs.writeJSON(assetPath, gltf)

  const storyPath = path.resolve(TARGET_DIR, `${slug}.stories.js`)
  await fs.ensureFile(storyPath)
  await fs.writeFile(storyPath, storyTemplate(assetFilename, title))
};
