import path from 'path'
import fs from 'fs-extra'
import { Asset, Scene, Node } from 'gltf-builder';
import slugify from '@sindresorhus/slugify'
import { GLTFStoryArgs, argTypesDefinition } from './story-template';

const TARGET_DIR = process.env.STORY_TARGET_DIR ?? process.cwd();

const storyTemplate = (importPath: string, title: string, args: Partial<GLTFStoryArgs>) => `// @autogenerated
import { gltfStoryTemplate } from '@gengarden/examples/build/lib/story-template';
import gltfAsset from 'file-loader!./${importPath}';

export default {
  title: '${title}',
  argTypes: JSON.parse('${JSON.stringify(argTypesDefinition)}')
};

export const GLTFModel = gltfStoryTemplate({ src: gltfAsset });
GLTFModel.args = JSON.parse('${JSON.stringify(args)}');
`

export const generateGLTFStory = async (title: string, model: Node, args: Partial<GLTFStoryArgs> = {}) => {
  const slug = slugify(title)

  const assetFilename = `${slug}.gltf`
  const assetPath = path.resolve(TARGET_DIR, assetFilename)
  const gltf = new Asset().addScene(new Scene().addNode(model)).build();

  await fs.ensureFile(assetPath)
  await fs.writeJSON(assetPath, gltf)

  const storyPath = path.resolve(TARGET_DIR, `${slug}.stories.js`)
  await fs.ensureFile(storyPath)
  await fs.writeFile(storyPath, storyTemplate(assetFilename, title, args))
};
